In [6]:
employee = []
again = "y"
while again == "y":
    detail = {}
    name = input("Enter Name: ")
    age = int(input("Enter Age: "))
    work = input("Enter Work Feild: ")
    skills = input("Enter 3 Skills sperated by comma(,): ").split(",")
    degree_title = input("Enter Degree Title: ")
    degree_major = input("Enter Major Subject: ")
    degree_end_date = input("Enter Completion Date: ")
    degree = {"title" : degree_title, "major" : degree_major, "completionDate" : degree_end_date}
    salary = int(input("Enter Your Salary"))
    detail = {"name" : name,
             "age" : age,
             "work" : work,
             "skills" : skills,
             "degree" : degree,
             "salary" : salary}
    employee.append(detail)
    correct = 1
    while correct == 1:
        again = input("Do you want to add another detail? (y/n)")
        if again == "y" or again == "n":
            correct = 0
        else:
            print("Please Enter Only \"y\" or \"n\". (y/n) \n")
            correct = 1

Enter Name: Danish
Enter Age: 22
Enter Work Feild: Graphics
Enter 3 Skills sperated by comma(,): Graphics, Android, Python
Enter Degree Title: BS
Enter Major Subject: Computer Science
Enter Completion Date: April 2019
Enter Your Salary20000
Do you want to add another detail? (y/n)y
Enter Name: Usama
Enter Age: 22
Enter Work Feild: Android
Enter 3 Skills sperated by comma(,): Android, Java, Python
Enter Degree Title: BS
Enter Major Subject: Software Engineering
Enter Completion Date: June 2019
Enter Your Salary25000
Do you want to add another detail? (y/n)n

In [7]:
employee

[{'name': 'Danish',
  'age': 22,
  'work': 'Graphics',
  'skills': ['Graphics', ' Android', ' Python'],
  'degree': {'title': 'BS',
   'major': 'Computer Science',
   'completionDate': 'April 2019'},
  'salary': 20000},
 {'name': 'Usama',
  'age': 22,
  'work': 'Android',
  'skills': ['Android', ' Java', ' Python'],
  'degree': {'title': 'BS',
   'major': 'Software Engineering',
   'completionDate': 'June 2019'},
  'salary': 25000}]

In [11]:
start_table = int(input("Enter Start Table: "))
end_table = int(input("Enter End Table: "))
for i in range(start_table,end_table+1):
    for j in range(1, 11):
        print(f"{i} * {j} = {j * i}")
    print("\n")
for i in range(1, 11):
    for j in range(start_table,end_table+1):
        print(f"{j} * {i} = {j * i}", end="\t")
    print("")

Enter Start Table: 5
Enter End Table: 10
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60


7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70


8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80


9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


5 * 1 = 5	6 * 1 = 6	7 * 1 = 7	8 * 1 = 8	9 * 1 = 9	10 * 1 = 10
5 * 2 = 10	6 * 2 = 12	7 * 2 = 14	8 * 2 = 16	9 * 2 = 18	10 * 2 = 20
5 * 3 = 15	6 * 3 = 18	7 * 3 = 21	8 * 3 = 24	9 * 3 = 27	10 * 3 = 30
5 * 4 = 20	6 * 4 = 24	7 * 4 = 28	8 * 4 = 32	9 * 4 = 36	10 * 4 = 40
5 * 5 = 25	6 * 5 = 30	7 * 5 = 35	8 * 5 = 40	9 * 5 = 45	10 * 5 = 50
5 * 6 = 30	6 * 6 = 36	7 * 6 = 42	8 * 6 = 48	9 * 6 = 54	10 * 6 = 60
5 * 7 = 35	6 * 7 = 42	7 * 7 = 49	8 * 7 = 56	9 * 7 = 63	10 * 7 = 70
5 * 8 = 40	6 * 8 = 48	7 * 8 = 56	8 * 8 = 64	9 * 8 = 72	10 * 8 = 80
5 * 9 = 45	6 * 9 = 54	7 * 9 = 63	8 * 9 = 72	9 * 9 = 81	10 * 9 = 90
5 * 10 = 50	6 * 10 = 60	7 * 10 = 70	8 * 10 = 80	9 * 10 = 90	10 * 10 = 100